### ISSUE TITLE
Removing Retrolambda

### ISSUE THREAD

**Issue by lucas34** [Piasy/RxAndroidAudio#35]
Hi,

You are using retrolambda in the lib. But since gradle 2.4.0 Some java 8 features' like lambda are supported natively. But retrolambda as to be removed (even from the libs).

Can you consider building the lib with 2.4.0 and removing it ?
We will also save 1 dex method per lambda. As retrolambda generate 4 but gradle 2.4.0 only 3.

Lucas

**Comment by lucas34** [comment]
Awesome !

**Comment by JakeWoki** [comment]
做为第三方库我觉得没必要限制为java1.8

**Comment by Piasy** [comment]
@JakeWoki I've never forced library users to use Java 1.8, have I?

B.T.W, speaking Chinese under an issue opened by English speaker is rude, very rude, lol.

**Comment by JakeWoki** [comment]
Error:Error converting bytecode to dex:
Cause: Dex cannot parse version 52 byte code.
This is caused by library dependencies that have been compiled using Java 8 or above.
If you are using the 'java' gradle plugin in a library submodule add 
targetCompatibility = '1.7'
sourceCompatibility = '1.7'
to that submodule's build.gradle file.
...while parsing com/github/piasy/rxandroidaudio/AudioRecorder.class
-----
/RxAndroidAudio/rxandroidaudio/build.gradle
compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
 }
becase I don't say English.If can add a switch to close the log?

**Comment by Piasy** [comment]
Well, it seems I should still use RetroLambda...

**Comment by JakeWoki** [comment]
no,don't use lambda in library

**Comment by Piasy** [comment]
Of course I'll use lambda in lib, lol.
